name: Bug
description: Report a bug
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: os
    attributes:
      label: Operating System
      description: "Which operating system do you use? Please provide the oversion as well."
      placeholder: "Debian linux (ARM)"
    validations:
      required: true  
  - type: input
    id: java
    attributes:
      label: Java or JDK Version
      description: "Please provide the full Java or JDK version of your project."
      placeholder: "v8.6.1"
    validations:
      required: true
  - type: input
    id: package
    attributes:
      label: Package Version
      description: "Please provide the full package version."
      placeholder: "javaplus 8.0.7, built: Jun  4 2021 01:50:04"
    validations:
      required: true
  - type: dropdown
    id: location
    attributes:
      label: Project Location
      description: Where is the project located?
      options:
        - Local
        - Remote
        - Somewhere else (please specify in the description!)
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
